# Generated by Django 6.0.3 on 2026-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('pastor', 'Pastor'), ('administrator', 'Administrator'), ('finance', 'Finance Officer'), ('cellleader', 'Cell Leader'), ('evangelism', 'Evangelism Team')], default='cellleader', max_length=20),
        ),
    ]
